services:
  # --- BANCO DE DADOS ---
  postgres_infra:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: totem
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: totem
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - totem-net

  # --- BACKEND (NODE.JS) ---
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - ./back/.env
    ports:
      - "2345:2345"
    volumes:
      - ./public/audios:/app/public/audios
    depends_on:
      - postgres_infra
    networks:
      - totem-net

  # --- FRONTEND (NEXT.JS) ---
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file:
      - ./front/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - totem-net
    volumes:
      - ./public/videos:/app/public/videos

volumes:
  pgdata:

networks:
  totem-net:
    driver: bridge