"use client";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, ImagePlay, Plus, Save, Trash2, Upload } from "lucide-react";
type Media = { name: string; url: string; type: "video" | "image" }; type Playlist = { id: string; name: string; items: string[] }; type Data = { files: Media[]; playlists: Playlist[]; activePlaylistId: string | null; imageDurationSeconds: number };
const initial: Data = { files: [], playlists: [], activePlaylistId: null, imageDurationSeconds: 10 };
export default function Page() {
  const [data, setData] = useState(initial); const [selected, setSelected] = useState(""); const [message, setMessage] = useState(""); const active = data.playlists.find((p) => p.id === selected);
  async function load() { const res = await fetch("/api/media", { cache: "no-store" }); const value = await res.json(); setData(value); setSelected((current) => current || value.activePlaylistId || value.playlists[0]?.id || ""); }
  useEffect(() => { void load(); }, []);
  async function upload(files: FileList | null) { if (!files?.length) return; const form = new FormData(); [...files].forEach((file) => form.append("files", file)); const res = await fetch("/api/media", { method: "POST", body: form }); setMessage(res.ok ? "Upload concluído." : (await res.json()).error); await load(); }
  function addPlaylist() { const id = `playlist-${Date.now()}`; setData({ ...data, playlists: [...data.playlists, { id, name: "Nova playlist", items: [] }] }); setSelected(id); }
  function updateActive(change: (list: Playlist) => Playlist) { setData({ ...data, playlists: data.playlists.map((list) => list.id === selected ? change(list) : list) }); }
  async function save() { const res = await fetch("/api/media", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); setMessage(res.ok ? "Playlists salvas." : (await res.json()).error); if (res.ok) await load(); }
  async function removeFile(name: string) { if (!confirm(`Excluir ${name}?`)) return; await fetch(`/api/media?name=${encodeURIComponent(name)}`, { method: "DELETE" }); await load(); }
  return <main className="p-5 md:p-10"><div className="mx-auto max-w-6xl"><header className="mb-8 flex items-center gap-4"><span className="rounded-2xl bg-fuchsia-600 p-3 text-white"><ImagePlay /></span><div><p className="text-sm font-bold uppercase tracking-widest text-fuchsia-600">Painéis</p><h1 className="text-3xl font-bold">Mídias e playlists</h1></div></header>
    <section className="mb-6 rounded-2xl border bg-white p-5 shadow-sm"><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white"><Upload size={18} />Enviar imagens ou vídeos<input className="hidden" type="file" multiple accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/ogg" onChange={(e) => void upload(e.target.files)} /></label><p className="mt-2 text-sm text-slate-500">Até 250 MB por arquivo.</p></section>
    <div className="grid gap-6 lg:grid-cols-[1fr,1.4fr]"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold">Biblioteca</h2><span>{data.files.length} itens</span></div><div className="max-h-[520px] space-y-2 overflow-auto">{data.files.map((file) => <div key={file.name} className="flex items-center gap-3 rounded-xl border p-3"><span className="min-w-0 flex-1 truncate">{file.name}</span><button title="Adicionar à playlist" disabled={!active || active.items.includes(file.name)} onClick={() => updateActive((list) => ({ ...list, items: [...list.items, file.name] }))} className="rounded-lg p-2 hover:bg-blue-50 disabled:opacity-30"><Plus /></button><button title="Excluir arquivo" onClick={() => void removeFile(file.name)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 /></button></div>)}</div></section>
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex flex-wrap gap-3"><select value={selected} onChange={(e) => setSelected(e.target.value)} className="min-w-48 flex-1 rounded-xl border px-3">{data.playlists.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><button onClick={addPlaylist} className="rounded-xl border px-4 py-2 font-bold"><Plus className="inline" size={18} /> Playlist</button>{active && <button onClick={() => { const remaining = data.playlists.filter((p) => p.id !== selected); setData({ ...data, playlists: remaining, activePlaylistId: data.activePlaylistId === selected ? remaining[0]?.id ?? null : data.activePlaylistId }); setSelected(remaining[0]?.id ?? ""); }} className="rounded-xl border px-3 text-red-600"><Trash2 /></button>}</div>
      {active && <><input value={active.name} onChange={(e) => updateActive((p) => ({ ...p, name: e.target.value }))} className="mb-4 w-full rounded-xl border px-4 py-3 font-bold" /><label className="mb-4 flex items-center gap-3"><input type="radio" checked={data.activePlaylistId === active.id} onChange={() => setData({ ...data, activePlaylistId: active.id })} />Usar esta playlist no painel</label><label className="mb-5 block">Duração das imagens: <input type="number" min={2} max={300} value={data.imageDurationSeconds} onChange={(e) => setData({ ...data, imageDurationSeconds: Number(e.target.value) })} className="ml-2 w-20 rounded-lg border p-2" /> segundos</label><div className="space-y-2">{active.items.map((name, index) => <div key={name} className="flex items-center gap-2 rounded-xl bg-slate-50 p-3"><span className="min-w-0 flex-1 truncate">{index + 1}. {name}</span><button disabled={!index} onClick={() => updateActive((p) => { const items = [...p.items]; [items[index - 1], items[index]] = [items[index], items[index - 1]]; return { ...p, items }; })}><ArrowUp /></button><button disabled={index === active.items.length - 1} onClick={() => updateActive((p) => { const items = [...p.items]; [items[index + 1], items[index]] = [items[index], items[index + 1]]; return { ...p, items }; })}><ArrowDown /></button><button onClick={() => updateActive((p) => ({ ...p, items: p.items.filter((item) => item !== name) }))} className="text-red-600"><Trash2 /></button></div>)}</div></>}
      <button onClick={() => void save()} className="mt-6 flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white"><Save size={18} />Salvar</button>{message && <p className="mt-3 font-semibold">{message}</p>}</section></div></div></main>;
}
